//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Context_Layers.Dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int Movie_ID { get; set; }
        public string Movie_Name { get; set; }
        public string Hero { get; set; }
        public string Heroin { get; set; }
        public string Director { get; set; }
        public string Movie_Ticket { get; set; }
    }
}
